### PR TITLE
initial server - skeleton

### PR DESCRIPTION
**Pull request by kaihsia**
This is barebone atm.  Will be testing out graphql and ws architecture.

### CODE REVIEW

**Comment by zoetrope6** [comment]
DOPE thanks so much... i'm a noob with GitHub, how do i see the changes?
Also, do you think we could use put this open-source code to good use?
https://codepen.io/mjweaver01/pen/LpaMzz

**Comment by zoetrope6** [comment]
i merged your work, should there be any changes when i open up the
index.html file?

**Comment by kaihsia** [comment]
I made it so the client files are being served up thru your machine.  So, just open up your terminal, navigate to the root folder of your project (where package.json is) and follow the instructions on the README.  We will need to talk about the stack communication when I get back from la.

**Comment by zoetrope6** [comment]
in terminal i only see the firebase.json file that i've had since the
beginning. would merging have added the files you have made on github into
that folder on my machine?

**Comment by kaihsia** [comment]
Ohh do a 'git pull --rebase origin master' on the root folder. Call me if
there any conflicts

**Pull request merged**
